// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "../Time.hpp"

// =====================
// Test the default constructor
// ---------------------

TEST_CASE("ex0", "[Default time]")
{
    Time t;

    SECTION("Default constructor") {
        REQUIRE(t.getHour()==0);
        REQUIRE(t.getMinute()==0);
    }
}

// =====================
// Test the parameterized constructor
// ---------------------

TEST_CASE("ex1", "[Parameterized time]")
{
    Time t(3,15);

    SECTION("Parameterized constructor") {
        REQUIRE(t.getHour()==3);
        REQUIRE(t.getMinute()==15);
    }
}

// =====================
// Test setters y getters
// ---------------------

TEST_CASE("ex2", "[Time's setters y getters]")
{
    Time t;

    SECTION("Setters y getters") {
        t.setHour(3);
        t.setMinute(7);
        REQUIRE(t.getHour()==3);
        REQUIRE(t.getMinute()==7);
    }
}

// =====================
// Test elapsed time 
// ---------------------

TEST_CASE("ex3", "[elapsed time]")
{
    Time t1(8, 30), t2(9, 15);
    int elapsed;

    SECTION("Calculate elapsed time") {
        elapsed = t1.elapsedTime(t2);
        REQUIRE(elapsed == 45);
    }
}

